version: '3'
services:
  my-application1:
    image: my-first-app:2.0
    environment:
      SLEEP_TIME: 5
      CUSTOM_VARIABLE: "Yohohoho and bottle of Rom"
    volumes:
    - "./some-file.txt:/file-inside-container1.txt" # 1 way how to map volume

  my-application2:
    image: my-first-app:2.0
    environment:
      SLEEP_TIME: 100
    volumes:
    - "./some-file.txt:/file-inside-container2.txt"